config/routes.rb
Rails.application.routes.draw do
  resources :avaluos
  resources :avaluos, except: [:new,:index]
  root to: 'statics#index'

  devise_for :users, :controllers => {:registrations => "custom/registrations"}
  devise_for :admins, skip: [:registrations]
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
    delete 'admins' => 'devise/registrations#destroy', :as => 'destroy_admins_registration'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :admins, except: [:edit,:update] do
    collection do
      get 'create-requests', to: "admins#create_requests"
      post 'requests', to: "admins#requests"
      get 'create-pdf', to: "admins#create_pdf"
    end
  end

  resources :users, only: [:index,:show,:destroy]
  controller :statics do
    get 'requests', to: "statics#requests"
    get 'reports', to: "statics#reports"
    post 'statistics', to: "statics#statistics"
  end
  resources :clients
end

app/views/admins/_form.html.erb
<div class="form_admin">
	<%= form_for admin do |f| %>
	<% if admin.errors.any? %>
	<div id="error_explanation">
		<h2><%= t("admin.being_saved",count: admin.errors.count) %> </h2>
		<ul>
			<% admin.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<div class="form-group row">
		<div class="field col-md-6">
			<%= f.text_field :name, placeholder: :name, autofocus: true %>
		</div>

		<div class="field col-md-6">
			<%= f.text_field :lastname , placeholder: :lastname %>
		</div>
	</div>
	<div class="field email">
		<%= f.email_field :email, placeholder: :email %>
	</div>
	<div class="form-group row">
		<div class="field col-md-6">
			<%= f.text_field :username, placeholder: :username %>
		</div>
		<div class="field col-md-6">
			<%= f.text_field :mobile, placeholder: :mobile %>
		</div>
	</div>
	<div class="form-group row">
		<div class="field col-md-6">
			<%= f.password_field :password, placeholder: "Password (6 characters minimum)", autocomplete: "off" %>
		</div>
		<div class="field col-md-6">
			<%= f.password_field :password_confirmation, placeholder: "Password Confirmation", autocomplete: "off" %>
		</div>
	</div>

	<div class="actions">
		<%= f.submit "Crear administrador" %>
	</div>

	<% end %>
</div>

app/views/admins/_paginate.html.erb
<%= will_paginate @admins, renderer: BootstrapPagination::Rails %>

app/views/admins/create_requests.html.erb
<%= stylesheet_link_tag 'admins', media: 'all', type:"text/css" %>

<section class="create_request container">
	<div class="logo">
		<%= image_tag "logo_isa.png", :class => "logo img-responsive" %>
	</div>
	<h2 class="title">Asignar avaluo a un perito</h2>
	<div class="categories">
		<%= form_with(url: requests_admins_path, local: true, id: 'avaluo') do |form| %>
		<div class="form-group row">
			<div class="option col-md-4">
				<label>Categoría nivel 1:</label>
				<%= select_tag(:nivel_one, options_for_select([['Seleccionar categoria nivel 1', 0], ['Inmuebles', 1], ['Muebles', 3]])) %>
			</div>
			<div class="option col-md-4">
				<label>Categoría nivel 2:</label>
				<%= select_tag(:nivel_two, options_for_select([['Seleccionar categoria nivel 2', 0]])) %>
			</div>
			<div class="option col-md-4">
				<label>Categoría nivel 3:</label>
				<%= select_tag(:nivel_three, options_for_select([['Seleccionar categoria nivel 3', 0]])) %>
			</div>
		</div>
		<div class="form-group row">
			<div class="option col-md-4">
				<label>Seleccione un perito:</label>
				<%= select_tag "peritos", options_from_collection_for_select(@peritos, "id", "email") %>
			</div>
			<div class="option col-md-4">
				<label>Seleccione el tipo de cliente:</label>
				<%= select_tag "clientes", options_from_collection_for_select(@clientes, "id", "name") %>
			</div>
			<div class="option col-md-4">
				<button type="submit">Enviar</button>
			</div>
		</div>
		<% end %>
	</div>
</section>

app/views/admins/index.html.erb
<%= stylesheet_link_tag 'admins', media: 'all', type:"text/css" %>

<section class="home_admin">
	<!--<h1><%= t("admins.title")%> </h1>-->
	<div class="logo">
		<%= image_tag "logo_isa.png", :class => "logo img-responsive" %>
	</div>
	<%= link_to t("admins.log_out"), destroy_admin_session_path, method: :delete, :class=>"logout"  %>
	
	<div class="admin_users">
		<% @admins.each do |a| %>
		<h3 class="current_user">
			<%= a.name %> <%= a.lastname %> - <%= a.username %>
		</h3>
		<p>
			<% if current_admin.id != a.id %>
			<%= link_to t("admins.destroy"), a, method: :delete, data: { confirm: 'Are you sure?'}  %>
			<% end %>
		</p>
	</div>

	<div class="admin_actions clearfix">
		<div class="action">
			<%= link_to new_admin_path, :class=>"item" do %>
			<%= icon('user-plus') + " " + t("admins.new") %>
			<% end %>
		</div>
		<div class="action">
			<%= link_to users_path, :class=>"item" do %>
			<%= icon('users') + " " + t("users.title") %>
			<% end %>	
		</div>
		<div class="action">
			<%= link_to edit_admin_registration_path(current_admin), :class=>"item" do %>
			<%= icon('pencil-square-o') + " " + t("admins.edit") %>
			<% end %>
		</div>
		<div class="action">
			<%= link_to new_client_path, :class=>"item" do %>
			<%= icon('plus') + " " + t("clients.new") %>
			<% end %>
		</div>
		<div class="action">
			<%= link_to create_requests_admins_path, :class=>"item" do %>
			<%= icon('plus-circle') %> Crear nuevo avaluo
			<% end %>
		</div>
	</div>

	<% end %>

	<%= render 'paginate' %>

</section>

app/views/admins/new.html.erb
<%= stylesheet_link_tag 'admins', media: 'all', type:"text/css" %>
<section class="new_form">
	<div class="logo">
		<%= image_tag "logo_isa.png", :class => "logo img-responsive" %>
	</div>
	<h1 class="title"><%= t("admins.new") %></h1>

	<%= render 'form', admin: @admin %>
</section>

app/views/admins/requests.html.erb
<h1>Hola</h1>

app/views/admins/show.html.erb
<h1><%= t("admins.show") %></h1>

<p><%= @admin.name %></p>
<p><%= @admin.lastname %></p>
<p><%= @admin.username %></p>
<p><%= @admin.mobile %></p>

<%= link_to t("admins.back"), admins_path %>