config/routes.rb
Rails.application.routes.draw do
  resources :avaluos
  resources :avaluos, except: [:new,:index]
  root to: 'statics#index'

  devise_for :users, :controllers => {:registrations => "custom/registrations"}
  devise_for :admins, skip: [:registrations]
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
    delete 'admins' => 'devise/registrations#destroy', :as => 'destroy_admins_registration'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :admins, except: [:edit,:update] do
    collection do
      get 'create-requests', to: "admins#create_requests"
      post 'requests', to: "admins#requests"
      get 'create-pdf', to: "admins#create_pdf"
    end
  end

  resources :users, only: [:index,:show,:destroy]
  controller :statics do
    get 'requests', to: "statics#requests"
    get 'reports', to: "statics#reports"
    post 'statistics', to: "statics#statistics"
  end
  resources :clients
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  before_action :authenticate, only: [:requests]
  before_action :authenticate_admin!, only: [:reports]

  def index
  end

  def reports
  end

  def statistics
    @results = {}
    if params[:tipo_grafico] == "Torta"
      @type = "pie_chart"
      @title = "Estados de avaluos y Estados de revison"
      if  params[:avaluo_type] == "Todos"
        if params[:estado] == "Estado avaluo"
          @title = "Estados de avaluos"
          ["Inmuble-Rural-Casa rural","Inmueble-Rural-Lote","Inmueble-Urbano-Apartamento",
          "Inmueble-Urbano-Bodega","Inmueble-Urbano-Casa","Inmueble-Urbano-Local","Inmueble-Urbano-Lote urbano",
          "Inmueble-Urbano-Lote Oficina"].each do |k|
            t = Avaluo.where(
              avaluo_type: Avaluo.avaluo_types[k]
            ).where(estado_avaluo: 0).count
            t1 = Avaluo.where(
              avaluo_type: Avaluo.avaluo_types[k]
            ).where(estado_avaluo: 1).count
            t2 = Avaluo.where(
              avaluo_type: Avaluo.avaluo_types[k]
            ).where(estado_avaluo: 2).count
            t3 = Avaluo.where(
              avaluo_type: Avaluo.avaluo_types[k]
            ).where(estado_avaluo: 3).count

            @results["#{k}-nuevo"] = t
            @results["#{k}-en progreso"] = t1
            @results["#{k}-en revision"] = t2
            @results["#{k}-finalizado"] = t3
          end
        else
          @title = "Estados de revison"
          ["Inmuble-Rural-Casa rural","Inmueble-Rural-Lote","Inmueble-Urbano-Apartamento",
          "Inmueble-Urbano-Bodega","Inmueble-Urbano-Casa","Inmueble-Urbano-Local","Inmueble-Urbano-Lote urbano",
          "Inmueble-Urbano-Lote Oficina"].each do |k|
            t = Avaluo.where(
              avaluo_type: Avaluo.avaluo_types[k]
            ).where(estado_avaluo: 2).where(estado_revison: 0).count
            t1 = Avaluo.where(
              avaluo_type: Avaluo.avaluo_types[k]
            ).where(estado_avaluo: 2).where(estado_revison: 0).count
            t2 = Avaluo.where(
              avaluo_type: Avaluo.avaluo_types[k]
            ).where(estado_avaluo: 2).where(estado_revison: 0).count
            @results["#{k}-revision-sin revision"] = t
            @results["#{k}-revision-revisando"] = t1
            @results["#{k}-revision-revisado"] = t2
          end
        end
      else
        if params[:estado] == "Estado avaluo"
          @title = "Estados de avaluos"
          t = Avaluo.where(
            avaluo_type: Avaluo.avaluo_types[params[:avaluo_type]]
          ).where(estado_avaluo: 0).count
          t1 = Avaluo.where(
            avaluo_type: Avaluo.avaluo_types[params[:avaluo_type]]
          ).where(estado_avaluo: 1).count
          t2 = Avaluo.where(
            avaluo_type: Avaluo.avaluo_types[params[:avaluo_type]]
          ).where(estado_avaluo: 2).count
          t3 = Avaluo.where(
            avaluo_type: Avaluo.avaluo_types[params[:avaluo_type]]
          ).where(estado_avaluo: 3).count
          @results["#{params[:avaluo_type]}-nuevo"] = t
          @results["#{params[:avaluo_type]}-en progreso"] = t1
          @results["#{params[:avaluo_type]}-en revision"] = t2
          @results["#{params[:avaluo_type]}-finalizado"] = t3
        else
          @title = "Estados de revison"
          t = Avaluo.where(
            avaluo_type: Avaluo.avaluo_types[params[:avaluo_type]]
          ).where(estado_avaluo: 2).where(estado_revison: 0).count
          t1 = Avaluo.where(
            avaluo_type: Avaluo.avaluo_types[params[:avaluo_type]]
          ).where(estado_avaluo: 2).where(estado_revison: 0).count
          t2 = Avaluo.where(
            avaluo_type: Avaluo.avaluo_types[params[:avaluo_type]]
          ).where(estado_avaluo: 2).where(estado_revison: 0).count
          @results["#{params[:avaluo_type]}-revision-sin revision"] = t
          @results["#{params[:avaluo_type]}-revision-revisando"] = t1
          @results["#{params[:avaluo_type]}-revision-revisado"] = t2
        end
      end
    else
      @type = "bar_chart"
      @results = []
      data = {}
      if params[:avaluo_type] == "Todos"
        ["Inmuble-Rural-Casa rural","Inmueble-Rural-Lote","Inmueble-Urbano-Apartamento",
        "Inmueble-Urbano-Bodega","Inmueble-Urbano-Casa","Inmueble-Urbano-Local","Inmueble-Urbano-Lote urbano",
        "Inmueble-Urbano-Lote Oficina"].each do |k|
          values = []
          data = {}
          Client.all.each  do |m|
            values << [m.name,Avaluo.where(client_id: m.id).where(avaluo_type: Avaluo.avaluo_types[k]).count]
          end
          data[:name] = k
          data[:data] = values
          @results << data
        end
      else
        values = []
        Client.all.each do |m|
          values << [m.name,Avaluo.where(client_id: m.id).where(avaluo_type: Avaluo.avaluo_types[params[:avaluo_type]]).count]
        end
        data[:name] = params[:avaluo_type]
        data[:data] = values
        @results << data
      end
      p @results

    end
  end

  def requests
    if current_user
      ids = AvaluoUser.where(
        user_id: current_user.id
      ).pluck(:avaluo_id)
      @avaluos = Avaluo.where(
        id: ids
      )
      if current_user.Perito?
        @avaluos = @avaluos.where(estado_avaluo: [0,1])
      else
        @avaluos = @avaluos.where(estado_avaluo: [2])
      end
    else
      @avaluos = Avaluo.where(estado_avaluo: 3)
    end

  end
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/statics/_bar_chart.html.erb
<%= bar_chart @results,id: "chart", adapter: "highcharts", library: {
  title: {
        text: 'Avaluos por clientes'
    },
    legend: {
        reversed: true
    },
    plotOptions: {
        series: {
            stacking: 'normal'
        }
    }
  } %>

app/views/statics/_pie_chart.html.erb
<%= pie_chart @results, id: "chart", adapter: "highcharts",
library: {
  tooltip: {
    pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>' },
    title: { text: "#{@title}" },
    plotOptions: { pie: { allowPointSelect: true,
      cursor: 'pointer', dataLabels: { enabled: false },
      showInLegend: true }
    }
  }
%>

app/views/statics/index.html.erb
<%= stylesheet_link_tag 'statics', media: 'all', type:"text/css" %>

<section class="main">
	<div class="home_info">
		<div class="logo">
			<%= image_tag "logo_isa.png", :class => "logo img-responsive" %>
		</div>
		<div class="login_access">
			<div class="access">
				<%= link_to 'Log in admin', new_admin_session_path, :class => "link" %>
			</div>
			<div class="access">
				<%= link_to 'Log in user', new_user_session_path, :class => "link" %>
			</div>
		</div>
	</div>
</section>

app/views/statics/reports.html.erb
<h1>Estadisticas</h1>
<div class="x_panel">
  <div class="x_content">
    <%= form_tag statistics_path, method: :post, remote: true, class:"form-horizontal form-label-left" do %>
      <div class="form-group">
        <label class="control-label col-md-5 col-sm-5 col-xs-12" for="statistics">Tipo de grafico</label>
        <div class="col-md-4 col-sm-4 col-xs-12">
          <%= select_tag(:tipo_grafico, options_for_select( ["Torta","Barras"],"Torta"), {:include_blank => false, :class=>"form-control"} )%>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-md-5 col-sm-5 col-xs-12" for="statistics">Tipo de avaluos</label>
        <div class="col-md-4 col-sm-4 col-xs-12">
          <%= select_tag(:avaluo_type, options_for_select( ["Todos"] + Avaluo.avaluo_types.keys,"Todos"), {:include_blank => false, :class=>"form-control"} )%>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-md-5 col-sm-5 col-xs-12" for="statistics">Estado</label>
        <div class="col-md-4 col-sm-4 col-xs-12">
          <%= select_tag(:estado, options_for_select( ["Estado avaluo","Estado revison"] ,"Estado avaluo"), {:include_blank => false, :class=>"form-control"} )%>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-5">
          <%= submit_tag("Enviar", {:class=>"btn btn-success"} )%>
        </div>
      </div>
    <% end %>

    <div class="ln_solid"></div>

    <div id="results"></div>
  </div>
</div>

app/views/statics/requests.html.erb
<%= stylesheet_link_tag 'statics', media: 'all', type:"text/css" %>

<section class="valuations">
	<div class="logo">
		<%= image_tag "logo_isa.png", :class => "logo img-responsive" %>
	</div>
	<%= link_to t("admins.log_out"), destroy_user_session_path , method: :delete , :class => "logout" %>
	<h2 class="title">Avaluos</h2>
	<div class="content_info">
		<section class="data row">
			<div class="valuation_data col-md-2">Cliente</div>
			<div class="valuation_data col-md-2">Tipo de Avalúo</div>
			<div class="valuation_data col-md-2">Estado del Avalúo</div>
			<div class="valuation_data col-md-2">Tipo de Inmueble</div>
			<div class="valuation_data col-md-3">Ver Avalúo</div>
			<div class="valuation_data download col-md-1">Descargar</div>
		</section>
		<div class="show_data row">
			<% @avaluos.each do |a| %>
			<div class="client col-md-2">
				<p class="info"><%= a.client.name %></p>
			</div>
			<div class="avaluo_type col-md-2">
				<p class="info"><%= a.avaluo_type %></p>
			</div>
			<div class="estado_avaluo col-md-2">
				<p class="info"><%= a.estado_avaluo %></p>
			</div>
			<!--<% if current_user && !current_user.Perito? %>
			<p class="info"><%= a.estado_revison %></p>
			<% end %>-->
			<div class="inmueble_tipo col-md-2">
				<p class="info"><%= a.inmueble_tipo %></p>
			</div>
			<div class="edit_avaluo col-md-3">
				<p class="info"><%= link_to a.serial, edit_avaluo_path(a) %></p>
			</div>
			<div class="pdf col-md-1">
				<p class="info"><%= link_to "generar pdf", create_pdf_admins_path(format: "pdf",avaluo: a.id) %></p>
			</div>
			<!--<%= a.fecha_avaluo %>-->

			<% end %>
		</div>
	</div>
</section>

app/views/statics/statistics.js.erb
$('#results').html("<%= escape_javascript(render("#{@type}")) %>");