config/routes.rb
Rails.application.routes.draw do
  resources :avaluos
  resources :avaluos, except: [:new,:index]
  root to: 'statics#index'

  devise_for :users, :controllers => {:registrations => "custom/registrations"}
  devise_for :admins, skip: [:registrations]
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
    delete 'admins' => 'devise/registrations#destroy', :as => 'destroy_admins_registration'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :admins, except: [:edit,:update] do
    collection do
      get 'create-requests', to: "admins#create_requests"
      post 'requests', to: "admins#requests"
      get 'create-pdf', to: "admins#create_pdf"
    end
  end

  resources :users, only: [:index,:show,:destroy]
  controller :statics do
    get 'requests', to: "statics#requests"
    get 'reports', to: "statics#reports"
    post 'statistics', to: "statics#statistics"
  end
  resources :clients
end

app/models/avaluo.rb
class Avaluo < ApplicationRecord
  belongs_to :client
  has_many :avaluo_images
  has_many :avaluo_users
  has_many :users, through: :avaluo_users

  enum inmueble_clase: {
    "unifamiliar":0,
    "bifamiliar":1,
    "multifamiliar":2,
    "Viv. subsidiada":3,
    "industrial":4,
    "comercial":5,
    "ed oficinas":6
  }

  enum tipo_de_identificacion: {
    "C.C" => 0,
    "C.Ext" => 1,
    "Nit" => 2,
  }

  enum objeto_avaluo: {
    "organizacion": 0,
    "actualizacion":1,
    "reconsideracion":2,
    "correccion":3,
    "remate":4,
    "dacion en pago":5,
    "desafectacion":6,
    "normalizacion":7
  }
  enum metodologia_valutoria: {
    "comparacion de mercado":0,
    "capitalizacion de ingresos":1,
    "metodo de reposicion":2,
    "metodo residual":3,
    "comparacion-capitalizacion":4,
    "comparacion-reposicion":5,
    "comparacion-residual":6,
    "capitalizacion-reposicion":7,
    "capitalizacion-residual":8,
    "reposicion-residual":9,
    "comp-capit-repos":10,
    "comp-repos-residual":11,
    "comp-capit-residual":12,
    "comp-capit-repos-residual":13
  }

  enum inmueble_uso: {
    "vivienda":0,
    "comercio":1,
    "bodega":2,
    "oficina":3,
    "V multihabitacioinal":4,
    "educacion":5,
    "salud":6,
    "hotelero":7,
    "_industrial":8,
    "iglesia":9,
    "parqueadero":10,
    "auditorio":11,
    "instalacion deportiva":12
  }

  enum estado_avaluo: {
    "nuevo" => 0,
    "en progreso" => 1,
    "en revison" => 2,
    "finalizado" => 3,
  }


  enum inmueble_tipo_vivienda: {
    "vis":0,
    "no vis":1
  }

  enum inmueble_ubicacion: {
    "esquinero":0,
    "medianero":1
  }

  enum sistemas_de_coordenadas: {
    "magna sirgas": 0,
    "wgs82":1,
    "wgs84":2
  }

  enum estado_revison: {
    "sin revison" => 0,
    "revisando" => 1,
    "revisado" => 2,
  }

  enum avaluo_type: {
    "Inmuble-Rural-Casa rural" => 0,
    "Inmueble-Rural-Lote" => 1,
    "Inmueble-Urbano-Apartamento" => 2,
    "Inmueble-Urbano-Bodega" => 3,
    "Inmueble-Urbano-Casa" => 4,
    "Inmueble-Urbano-Local" => 5,
    "Inmueble-Urbano-Lote urbano" => 6,
    "Inmueble-Urbano-Lote Oficina" => 7,
  }



end

app/helpers/avaluos_helper.rb
module AvaluosHelper
end

app/views/avaluos/_form.html.erb
<%= form_with(model: avaluo,local: true, multipart: true) do |form| %>
<% if avaluo.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(avaluo.errors.count, "error") %> prohibited this avaluo from being saved:</h2>

	<ul>
		<% avaluo.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>




<section class="basic_info">
	<h4 class="name_section">Información Básica</h4>
	<div class="form_info">
		<div class="form-group row">
			<div class="field col-md-4">
				<%= form.label :nombre_solicitante %>
				<%= form.text_field :nombre_solicitante, id: :avaluo_nombre_solicitante %>
			</div>
			<div class="field col-md-4">
				<%= form.label :tipo_de_identificacion %>
				<%= form.select :tipo_de_identificacion,Avaluo.tipo_de_identificacions.keys.to_a, id: :avaluo_tipo_de_identificacion %>
			</div>
			<div class="field col-md-4">
				<%= form.label :numero_de_identificacion %>
				<%= form.text_field :numero_de_identificacion, id: :avaluo_numero_de_identificacion %>
			</div>
		</div>
		<div class="form-group row">
			<div class="field col-md-4">
				<%= form.label :objeto_avaluo %>
				<%= form.select :objeto_avaluo,Avaluo.objeto_avaluos.keys.to_a, id: :avaluo_objeto_avaluo %>
			</div>
		</div>
		<div class="form-group row">
			<div class="field col-md-4">
				<%= form.label :fecha_avaluo %>
				<%= form.date_select :fecha_avaluo, id: :avaluo_fecha_avaluo %>
			</div>
			<div class="field col-md-4">
				<%= form.label :fecha_correcion %>
				<%= form.date_select :fecha_correcion, id: :avaluo_fecha_correcion %>
			</div>
			<div class="field col-md-4">
				<%= form.label :metodologia_valutoria %>
				<%= form.select :metodologia_valutoria,Avaluo.metodologia_valutoria.keys.to_a, id: :avaluo_metodologia_valutoria %>
			</div>
		</div>
		<div class="form-group row">
			<div class="field col-md-4">
				<%= form.label :barrio %>
				<%= form.text_field :barrio, id: :avaluo_barrio %>
			</div>
			<div class="field col-md-4">
				<%= form.label :nombre_conjunto_o_edificio %>
				<%= form.text_field :nombre_conjunto_o_edificio, id: :avaluo_nombre_conjunto_o_edificio %>
			</div>
		</div>
		<div class="form-group row">
			<div class="field col-md-4">
				<%= form.label :departamento %>
				<%= form.text_field :departamento, id: :avaluo_departamento %>
			</div>
			<div class="field col-md-4">
				<%= form.label :ciudad %>
				<%= form.text_field :ciudad, id: :avaluo_ciudad %>
			</div>
		</div>
		<div class="form-group row">
			<div class="field col-md-4">
				<%= form.label :sistemas_de_coordenadas %>
				<%= form.select :sistemas_de_coordenadas,Avaluo.sistemas_de_coordenadas.keys.to_a, id: :avaluo_sistemas_de_coordenadas %>
				<div class="field">
					<%= form.label :sistemas_de_coordenadas_otra %>
					<%= form.text_field :sistemas_de_coordenadas_otra, id: :avaluo_sistemas_de_coordenadas_otra %>
				</div>
			</div>
			<div class="field col-md-4">
				<%= form.label :latitud %>
				<%= form.text_field :latitud, id: :avaluo_latitud %>
			</div>
			<div class="field col-md-4">
				<%= form.label :longitud %>
				<%= form.text_field :longitud, id: :avaluo_longitud %>
			</div>
		</div>
		<div class="form-group row">
			<div class="field col-md-12">
				<%= form.label :direccion_inmueble %>
				<%= form.text_field :direccion_inmueble, id: :avaluo_direccion_inmueble %>
			</div>
		</div>
		<div class="form-group row">
			<div class="field col-md-9">
				<%= form.label :justificacion_metodologia %>
				<%= form.text_area :justificacion_metodologia, id: :avaluo_justificacion_metodologia %>
			</div>
		</div>
	</div>
</section>

<section class="property_info">
	<h4 class="name_section">Información del Inmueble</h4>
	<div class="form_info">
		<div class="form-group five clearfix">
			<div class="field">
				<%= form.label :inmueble_tipo %>
				<%= form.text_field :inmueble_tipo, id: :avaluo_inmueble_tipo %>
			</div>
			<div class="field">
				<%= form.label :inmueble_uso %>
				<%= form.select :inmueble_uso,Avaluo.inmueble_usos.keys.to_a, id: :avaluo_inmueble_uso %>
			</div>
			<div class="field">
				<%= form.label :inmueble_uso_otro %>
				<%= form.text_field :inmueble_uso_otro, id: :avaluo_inmueble_uso_otro %>
			</div>
			<div class="field">
				<%= form.label :inmueble_clase %>
				<%= form.select :inmueble_clase, Avaluo.inmueble_clases.keys.to_a,id: :avaluo_inmueble_clase %>
			</div>
			<div class="field">
				<%= form.label :inmueble_clase_otro %>
				<%= form.text_field :inmueble_clase_otro, id: :avaluo_inmueble_clase_otro %>
			</div>
		</div>
		<div class="form-group row">
			<div class="field col-md-4">
				<%= form.label :m_inmob_principal_1 %>
				<%= form.text_field :m_inmob_principal_1, id: :avaluo_m_inmob_principal_1 %>
			</div>
			<div class="field col-md-4">
				<%= form.label :m_inmob_principal_2 %>
				<%= form.text_field :m_inmob_principal_2, id: :avaluo_m_inmob_principal_2 %>
			</div>
			<div class="field col-md-4">
				<%= form.label :m_inmob_gj_1 %>
				<%= form.text_field :m_inmob_gj_1, id: :avaluo_m_inmob_gj_1 %>
			</div>
		</div>
		<div class="form-group row">
			<div class="field col-md-3">
				<%= form.label :m_inmob_gj_2 %>
				<%= form.text_field :m_inmob_gj_2, id: :avaluo_m_inmob_gj_2 %>
			</div>
			<div class="field col-md-3">
				<%= form.label :m_inmob_gj_3 %>
				<%= form.text_field :m_inmob_gj_3, id: :avaluo_m_inmob_gj_3 %>
			</div>
			<div class="field col-md-3">
				<%= form.label :m_inmob_gj_4 %>
				<%= form.text_field :m_inmob_gj_4, id: :avaluo_m_inmob_gj_4 %>
			</div>
			<div class="field col-md-3">
				<%= form.label :m_inmob_gj_5 %>
				<%= form.text_field :m_inmob_gj_5, id: :avaluo_m_inmob_gj_5 %>
			</div>
		</div>
		<div class="form-group row">
			<div class="field col-md-4">
				<%= form.label :m_inmob_dp_1 %>
				<%= form.text_field :m_inmob_dp_1, id: :avaluo_m_inmob_dp_1 %>
			</div>
			<div class="field col-md-4">
				<%= form.label :m_inmobiliaria_dp_2 %>
				<%= form.text_field :m_inmobiliaria_dp_2, id: :avaluo_m_inmobiliaria_dp_2 %>
			</div>
			<div class="field col-md-4">
				<%= form.label :chip %>
				<%= form.text_field :chip, id: :avaluo_chip %>
			</div>
		</div>
		<div class="form-group five clearfix">
			<div class="field">
				<%= form.label :inmueble_num_escritura %>
				<%= form.text_field :inmueble_num_escritura, id: :avaluo_inmueble_num_escritura %>
			</div>
			<div class="field">
				<%= form.label :inmueble_num_notaria %>
				<%= form.text_field :inmueble_num_notaria, id: :avaluo_inmueble_num_notaria %>
			</div>
			<div class="field">
				<%= form.label :inmueble_fecha_escritura %>
				<%= form.date_select :inmueble_fecha_escritura, id: :avaluo_inmueble_fecha_escritura %>
			</div>
			<div class="field">
				<%= form.label :inmueble_depto %>
				<%= form.text_field :inmueble_depto, id: :avaluo_inmueble_depto %>
			</div>
			<div class="field">
				<%= form.label :inmueble_ciudad %>
				<%= form.text_field :inmueble_ciudad, id: :avaluo_inmueble_ciudad %>
			</div>
		</div>
		<div class="form-group row">
			<div class="field">
				<%= form.label :inmueble_ubicacion %>
				<%= form.select :inmueble_ubicacion,Avaluo.inmueble_ubicacions.keys.to_a, id: :avaluo_inmueble_ubicacion %>
			</div>
		</div>
	</div>
</section>

<section class="obs_info">
	<h4 class="name_section">Observaciones</h4>
	<div class="form_info">
		<div class="field">
			<%= form.label :observaciones_observaciones %>
			<%= form.text_area :observaciones_observaciones, id: :avaluo_observaciones_observaciones %>
		</div>
	</div>
</section>

<% if (current_user && current_user.Perito?)  %>
<div class="field">
	<label for="">Finalizado</label>
	<%=   check_box_tag 'finalizado' %>
</div>
<br>
<label for="">Imagenes</label>
<input type="file" name="images[]" id="photos" multiple />

<% elsif current_user %>
<div class="field">
	<label for="">Revison finalizado</label>
	<%=   check_box_tag 'finalizado_re' %>
</div>
<% end %>



<div class="actions">
	<%= form.submit %>
</div>
<% end %>

app/views/avaluos/edit.html.erb
<%= stylesheet_link_tag 'avaluos', media: 'all', type:"text/css" %>
<section class="main">
	<div class="logo">
		<%= image_tag "logo_isa.png", :class => "logo img-responsive" %>
	</div>
	<h2 class="title">Editing Avaluo</h2>
	<section class="avaluos_form">
		<%= render 'form', avaluo: @avaluo %>
	</section>
</section>

<%= link_to 'Show', @avaluo %> |
<%= link_to 'Back', requests_path %>

app/views/avaluos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Avaluos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre solicitante</th>
      <th>Tipo de identificacion</th>
      <th>Numero de identificacion</th>
      <th>Client</th>
      <th>Objeto avaluo</th>
      <th>Fecha avaluo</th>
      <th>Fecha correcion</th>
      <th>Metodologia valutoria</th>
      <th>Estado avaluo</th>
      <th>Estado revison</th>
      <th>Barrio</th>
      <th>Nombre conjunto o edificio</th>
      <th>Departamento</th>
      <th>Ciudad</th>
      <th>Sistemas de coordenadas</th>
      <th>Latitud</th>
      <th>Longitud</th>
      <th>Sistemas de coordenadas otra</th>
      <th>Direccion inmueble</th>
      <th>Justificacion metodologia</th>
      <th>Avaluo type</th>
      <th>Inmueble tipo</th>
      <th>Inmueble uso</th>
      <th>Inmueble uso otro</th>
      <th>Inmueble clase</th>
      <th>Inmueble clase otro</th>
      <th>Inmueble tipo vivienda</th>
      <th>M inmob principal 1</th>
      <th>M inmob principal 2</th>
      <th>M inmob gj 1</th>
      <th>M inmob gj 2</th>
      <th>M inmob gj 3</th>
      <th>M inmob gj 4</th>
      <th>M inmob gj 5</th>
      <th>M inmob dp 1</th>
      <th>M inmobiliaria dp 2</th>
      <th>Chip</th>
      <th>Inmueble ubicacion</th>
      <th>Inmueble num escritura</th>
      <th>Inmueble num notaria</th>
      <th>Inmueble fecha escritura</th>
      <th>Inmueble depto</th>
      <th>Inmueble ciudad</th>
      <th>Observaciones observaciones</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @avaluos.each do |avaluo| %>
      <tr>
        <td><%= avaluo.nombre_solicitante %></td>
        <td><%= avaluo.tipo_de_identificacion %></td>
        <td><%= avaluo.numero_de_identificacion %></td>
        <td><%= avaluo.client %></td>
        <td><%= avaluo.objeto_avaluo %></td>
        <td><%= avaluo.fecha_avaluo %></td>
        <td><%= avaluo.fecha_correcion %></td>
        <td><%= avaluo.metodologia_valutoria %></td>
        <td><%= avaluo.estado_avaluo %></td>
        <td><%= avaluo.estado_revison %></td>
        <td><%= avaluo.barrio %></td>
        <td><%= avaluo.nombre_conjunto_o_edificio %></td>
        <td><%= avaluo.departamento %></td>
        <td><%= avaluo.ciudad %></td>
        <td><%= avaluo.sistemas_de_coordenadas %></td>
        <td><%= avaluo.latitud %></td>
        <td><%= avaluo.longitud %></td>
        <td><%= avaluo.sistemas_de_coordenadas_otra %></td>
        <td><%= avaluo.direccion_inmueble %></td>
        <td><%= avaluo.justificacion_metodologia %></td>
        <td><%= avaluo.avaluo_type %></td>
        <td><%= avaluo.inmueble_tipo %></td>
        <td><%= avaluo.inmueble_uso %></td>
        <td><%= avaluo.inmueble_uso_otro %></td>
        <td><%= avaluo.inmueble_clase %></td>
        <td><%= avaluo.inmueble_clase_otro %></td>
        <td><%= avaluo.inmueble_tipo_vivienda %></td>
        <td><%= avaluo.m_inmob_principal_1 %></td>
        <td><%= avaluo.m_inmob_principal_2 %></td>
        <td><%= avaluo.m_inmob_gj_1 %></td>
        <td><%= avaluo.m_inmob_gj_2 %></td>
        <td><%= avaluo.m_inmob_gj_3 %></td>
        <td><%= avaluo.m_inmob_gj_4 %></td>
        <td><%= avaluo.m_inmob_gj_5 %></td>
        <td><%= avaluo.m_inmob_dp_1 %></td>
        <td><%= avaluo.m_inmobiliaria_dp_2 %></td>
        <td><%= avaluo.chip %></td>
        <td><%= avaluo.inmueble_ubicacion %></td>
        <td><%= avaluo.inmueble_num_escritura %></td>
        <td><%= avaluo.inmueble_num_notaria %></td>
        <td><%= avaluo.inmueble_fecha_escritura %></td>
        <td><%= avaluo.inmueble_depto %></td>
        <td><%= avaluo.inmueble_ciudad %></td>
        <td><%= avaluo.observaciones_observaciones %></td>
        <td><%= link_to 'Show', avaluo %></td>
        <td><%= link_to 'Edit', edit_avaluo_path(avaluo) %></td>
        <td><%= link_to 'Destroy', avaluo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Avaluo', new_avaluo_path %>

app/views/avaluos/new.html.erb
<h1>New Avaluo</h1>

<%= render 'form', avaluo: @avaluo %>

<%= link_to 'Back', avaluos_path %>

app/views/avaluos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre solicitante:</strong>
  <%= @avaluo.nombre_solicitante %>
</p>

<p>
  <strong>Tipo de identificacion:</strong>
  <%= @avaluo.tipo_de_identificacion %>
</p>

<p>
  <strong>Numero de identificacion:</strong>
  <%= @avaluo.numero_de_identificacion %>
</p>

<p>
  <strong>Client:</strong>
  <%= @avaluo.client %>
</p>

<p>
  <strong>Objeto avaluo:</strong>
  <%= @avaluo.objeto_avaluo %>
</p>

<p>
  <strong>Fecha avaluo:</strong>
  <%= @avaluo.fecha_avaluo %>
</p>

<p>
  <strong>Fecha correcion:</strong>
  <%= @avaluo.fecha_correcion %>
</p>

<p>
  <strong>Metodologia valutoria:</strong>
  <%= @avaluo.metodologia_valutoria %>
</p>

<p>
  <strong>Estado avaluo:</strong>
  <%= @avaluo.estado_avaluo %>
</p>

<p>
  <strong>Estado revison:</strong>
  <%= @avaluo.estado_revison %>
</p>

<p>
  <strong>Barrio:</strong>
  <%= @avaluo.barrio %>
</p>

<p>
  <strong>Nombre conjunto o edificio:</strong>
  <%= @avaluo.nombre_conjunto_o_edificio %>
</p>

<p>
  <strong>Departamento:</strong>
  <%= @avaluo.departamento %>
</p>

<p>
  <strong>Ciudad:</strong>
  <%= @avaluo.ciudad %>
</p>

<p>
  <strong>Sistemas de coordenadas:</strong>
  <%= @avaluo.sistemas_de_coordenadas %>
</p>

<p>
  <strong>Latitud:</strong>
  <%= @avaluo.latitud %>
</p>

<p>
  <strong>Longitud:</strong>
  <%= @avaluo.longitud %>
</p>

<p>
  <strong>Sistemas de coordenadas otra:</strong>
  <%= @avaluo.sistemas_de_coordenadas_otra %>
</p>

<p>
  <strong>Direccion inmueble:</strong>
  <%= @avaluo.direccion_inmueble %>
</p>

<p>
  <strong>Justificacion metodologia:</strong>
  <%= @avaluo.justificacion_metodologia %>
</p>

<p>
  <strong>Avaluo type:</strong>
  <%= @avaluo.avaluo_type %>
</p>

<p>
  <strong>Inmueble tipo:</strong>
  <%= @avaluo.inmueble_tipo %>
</p>

<p>
  <strong>Inmueble uso:</strong>
  <%= @avaluo.inmueble_uso %>
</p>

<p>
  <strong>Inmueble uso otro:</strong>
  <%= @avaluo.inmueble_uso_otro %>
</p>

<p>
  <strong>Inmueble clase:</strong>
  <%= @avaluo.inmueble_clase %>
</p>

<p>
  <strong>Inmueble clase otro:</strong>
  <%= @avaluo.inmueble_clase_otro %>
</p>

<p>
  <strong>Inmueble tipo vivienda:</strong>
  <%= @avaluo.inmueble_tipo_vivienda %>
</p>

<p>
  <strong>M inmob principal 1:</strong>
  <%= @avaluo.m_inmob_principal_1 %>
</p>

<p>
  <strong>M inmob principal 2:</strong>
  <%= @avaluo.m_inmob_principal_2 %>
</p>

<p>
  <strong>M inmob gj 1:</strong>
  <%= @avaluo.m_inmob_gj_1 %>
</p>

<p>
  <strong>M inmob gj 2:</strong>
  <%= @avaluo.m_inmob_gj_2 %>
</p>

<p>
  <strong>M inmob gj 3:</strong>
  <%= @avaluo.m_inmob_gj_3 %>
</p>

<p>
  <strong>M inmob gj 4:</strong>
  <%= @avaluo.m_inmob_gj_4 %>
</p>

<p>
  <strong>M inmob gj 5:</strong>
  <%= @avaluo.m_inmob_gj_5 %>
</p>

<p>
  <strong>M inmob dp 1:</strong>
  <%= @avaluo.m_inmob_dp_1 %>
</p>

<p>
  <strong>M inmobiliaria dp 2:</strong>
  <%= @avaluo.m_inmobiliaria_dp_2 %>
</p>

<p>
  <strong>Chip:</strong>
  <%= @avaluo.chip %>
</p>

<p>
  <strong>Inmueble ubicacion:</strong>
  <%= @avaluo.inmueble_ubicacion %>
</p>

<p>
  <strong>Inmueble num escritura:</strong>
  <%= @avaluo.inmueble_num_escritura %>
</p>

<p>
  <strong>Inmueble num notaria:</strong>
  <%= @avaluo.inmueble_num_notaria %>
</p>

<p>
  <strong>Inmueble fecha escritura:</strong>
  <%= @avaluo.inmueble_fecha_escritura %>
</p>

<p>
  <strong>Inmueble depto:</strong>
  <%= @avaluo.inmueble_depto %>
</p>

<p>
  <strong>Inmueble ciudad:</strong>
  <%= @avaluo.inmueble_ciudad %>
</p>

<p>
  <strong>Observaciones observaciones:</strong>
  <%= @avaluo.observaciones_observaciones %>
</p>

<%= link_to 'Edit', edit_avaluo_path(@avaluo) %> |
<%= link_to 'Back', requests_path %>