config/routes.rb
Rails.application.routes.draw do
  resources :avaluos
  resources :avaluos, except: [:new,:index]
  root to: 'statics#index'

  devise_for :users, :controllers => {:registrations => "custom/registrations"}
  devise_for :admins, skip: [:registrations]
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
    delete 'admins' => 'devise/registrations#destroy', :as => 'destroy_admins_registration'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :admins, except: [:edit,:update] do
    collection do
      get 'create-requests', to: "admins#create_requests"
      post 'requests', to: "admins#requests"
      get 'create-pdf', to: "admins#create_pdf"
    end
  end

  resources :users, only: [:index,:show,:destroy]
  controller :statics do
    get 'requests', to: "statics#requests"
    get 'reports', to: "statics#reports"
    post 'statistics', to: "statics#statistics"
  end
  resources :clients
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t("devise.shared.links.sign_in"), new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to t("devise.shared.links.forgot_your_password"), new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to t("devise.shared.links.didn_t_receive_confirmation_instructions"), new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to t("devise.shared.links.didn_t_receive_unlock_instructions"), new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to t("devise.shared.links.sign_in_with_provider", provider: "#{OmniAuth::Utils.camelize(provider)}"), omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>